### ISSUE TITLE
Input an initial guess

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [paulknysh/blackbox#14]
Hello Paul,

Thank you for this nice piece of code :+1: 
Is it possible to feed the algorithm with an initial guess ? Or can you think of some clues to implement this ?

**Comment by paulknysh** [comment]
Hi,

Typically, "black-box" means that we don't know much about function, not even initial guess. That's why method doesn't support that. Instead, all we can guess about is the ranges of each parameter. Therefore, if you have some initial guess, all I can recommend for now is to set these ranges around your guess.

It is possible to add initial guess into the code. One would need to add some hacks into lines 87-93.
