### ISSUE TITLE
High dimensional optimization?

### ISSUE THREAD

**Issue by paulknysh** [paulknysh/blackbox#3]
I replaced Monte Carlo (for minimizing fit) with a SLSQP method from scipy.optimize library. The code now should be able to handle high dimensional cases.

Let me know if there are any issues.

**Comment by PilCAki** [comment]
How expensive a function is has absolutely zero relationship to the number of parameters that function has.

For example: a neural network may have hundreds of parameters, and may take a month for one function evaluation.

**Comment by paulknysh** [comment]
Well, this code is focusing mostly on expensive functions that need to be evaluated anyways - like physical simulations. I guess there are some different tricks to deal with neural nets because of their specific structure and properties. I thought evaluation of a given input in neural net is relatively cheap mostly.. But I'm not an expert on this so might be wrong.

**Comment by PilCAki** [comment]
To push a single sample into a neural net and get an output - yes, that's cheap.

To train a neural net and evaluate its performance - that's expensive.

Training and evaluating a neural net is like a function of possibly many params. It may run for hours or days, sometimes months for one set of params.

So - it is an expensive function that needs to be evaluated anyways.

There aren't really any specific tricks to deal with neural net params. Maybe a few rules of thumb,  but nothing I would say helps you much with automating architecture selection.

Anyway, the main point is that there's no relationship between expensive functions and the number of params.

A better way to describe blackbox would be "A black box optimizer for expensive, low dimensional optimization" if you consider >5D to be outside the scope of blackbox.

Otherwise, as you've observed, you'll get a lot of users attempting to apply it to high dimensonal problems - which is *not* out of the ordinary for expensive functions, contrary to what you've stated.

**Comment by paulknysh** [comment]
OK, that makes sense. Can you list few names of codes/methods that are commonly used for optimizing expensive functions with many parameters (in machine learning or other fields)?

**Comment by PilCAki** [comment]
Bayesian hyperparam optimization (Hyperopt)

Hyperband

Architecture Expansion

Random Search

There's a ton, just google it.

**Comment by paulknysh** [comment]
You're right, these and many others are methods for optimizing functions of high dimensions. However, again, the key question is how expensive the function they can handle. I've heard of successful usage of Bayesian approach (which is similar to what I use in **blackbox**), but it's not a silver bullet. I doubt about other methods. Random search and its variations (genetic algorithms) simply consume too many function evaluations so can't handle expensive functions.

**Comment by PilCAki** [comment]
Yep, not a silver bullet; but check out hyperband for instance. It does include a notion of "expense" and bakes that into the strategy.

All of these seek to find an optimum as quickly as possible.  Which is, of course, the exact thing you'd want to do for optimizing expensive functions.

**Comment by paulknysh** [comment]
I just replaced Monte Carlo with a SLSQP method from scipy.optimize library.

The code now should be able to handle high dimensional cases. Let me know if there any issues.
